repos:
  - repo: https://github.com/psf/black
    rev: 23.12.1  # Replace with latest if needed
    hooks:
      - id: black
        language_version: python3.11

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.4  # Replace with latest version
    hooks:
      - id: ruff
