name: Release on Merge to Main

on:
  push:
    branches:
      - main

permissions:
  contents: write
  id-token: write

jobs:
  release:
    if: github.repository == 'lytic-brew-mira/journal-backend'
    uses: lytic-brew-mira/infrastructure-ci/.github/workflows/full-release-template.yml@main
