name: Auto Tag on Merge

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  tag:
    uses: lytic-brew-mira/infrastructure-ci/.github/workflows/tag-release-template.yml@main
