name: Auto Tag on Merge

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  tag:
    if: github.repository == 'lytic-brew-mira/ai-journal-mvp'
    uses: lytic-brew-mira/infrastructure-ci/.github/workflows/tag-release-template.yml@main



